### ISSUE TITLE
Please update top of README

### ISSUE THREAD

**Issue by bruce-usab** [18F/jekyll-uswds#261]
## Background Information

During UWSDS webinar today (1/18/2024) mention was given of [implementations](https://designsystem.digital.gov/documentation/implementations/) and (since my agency site started with Federalist) I wanted to see the state of Jekyll support.  That implementation page leads leads to this repo.

At the top of the [readme](https://github.com/18f/uswds-jekyll#readme), is the statement:

> This repository is in maintenance mode and only accepting fixes. The Tech Portfolio and TTS Digital Council are working on a strategy for TTS microsites which will inform the future of this theme.

And the invitation to "Open an issue to provide any feedback."

Has the TTS Digital Council finalized the strategy for microsites.  If so, how did that inform the future of this theme?

I will note that README.md was last updated three years ago.

Please update the top of the README to reflect the current state of support.

Thanks very much.

## Implementation Steps

- [ ] README.md file updated with current status.

## Acceptance Criteria

- [ ] README.md clarifies disposition of TTS Digital Council on the topic of Jekyll support.
- [ ] Alternatively, USWDS Implementation page might change entry for USWDS-Jekyll to Stale or to be Archived
